// Mirrors sanitize() in src-tauri/src/lib.rs. That function is the security
// boundary; this copy exists so the server can predict a filename without
// asking the app. mcp/fixtures/sanitize-cases.json pins the two together —
// if you change one, the other's test fails.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const ILLEGAL = new Set(["/", "\\", ":", "*", "?", '"', "<", ">", "|", "\0"]);

// Load the Unicode classification from the fixture generated by Rust.
// This ensures we use exactly the same whitespace and control character
// definitions as the Rust implementation.
const classificationJson = JSON.parse(
  readFileSync(new URL("../fixtures/sanitize-classification.json", import.meta.url), "utf8"),
);

const WHITESPACE = new Set(classificationJson.whitespace);
const CONTROL = new Set(classificationJson.control);

export function sanitize(name) {
  // Replace illegal characters with dashes
  const cleaned = [...String(name ?? "")]
    .map((ch) => {
      const code = ch.codePointAt(0);
      if (ILLEGAL.has(ch) || CONTROL.has(code)) {
        return "-";
      }
      return ch;
    })
    .join("");

  // Trim whitespace, then dots, then whitespace again (matching Rust)
  let result = cleaned;

  // Trim leading whitespace
  while (result.length > 0 && WHITESPACE.has(result.codePointAt(0))) {
    result = result.substring(1);
  }

  // Trim trailing whitespace
  while (result.length > 0 && WHITESPACE.has(result.codePointAt(result.length - 1))) {
    result = result.substring(0, result.length - 1);
  }

  // Trim leading and trailing dots
  result = result.replace(/^\.+|\.+$/g, "");

  // Trim whitespace again
  while (result.length > 0 && WHITESPACE.has(result.codePointAt(0))) {
    result = result.substring(1);
  }

  while (result.length > 0 && WHITESPACE.has(result.codePointAt(result.length - 1))) {
    result = result.substring(0, result.length - 1);
  }

  if (result === "") return "Untitled";

  // Truncate to 120 characters (by Unicode scalar value, not by code units)
  return [...result].slice(0, 120).join("");
}
